# Generated by Django 2.0 on 2018-01-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioprojects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolioproject',
            options={'ordering': ['-order']},
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
